#define XMARGIN_WALL 6
#define XS 12
#define YMARGIN_WALL 6
#define YS 12
#define ZMARGIN_WALL 6
#define ZS 12
#define aij_in 4
#define aij_out 4
#define aij_rbc 4
#define aij_wall 4
#define gamma_dot 5.0
#define gammadpd_in 5.0
#define gammadpd_out 15.0
#define gammadpd_rbc 15.0
#define gammadpd_wall 15.0
#define hydrostatic_a 0.05
#define kBT 1e-7
#define ljepsilon 1.0
#define ljsigma 0.3
#define numberdensity 3
#define contactforces false
#define doublepoiseuille false
#define dt 0.0005
#define hdf5field_dumps false
#define hdf5part_dumps true
#define pushtheflow false
#define rbc_mass 0.5
#define rbcs true
#define rc 1.5
#define steps_per_dump 100
#define steps_per_hdf5dump 100
#define tend 0.5
#define wall_creation_stepid 100
#define walls true
