#define XMARGIN_WALL ( 6 )
#define XS ( 32 )
#define YMARGIN_WALL ( 6 )
#define YS ( 8 )
#define ZMARGIN_WALL ( 6 )
#define ZS ( 32 )
#define aij_in (( 4 ) / rc)
#define aij_in_out (( 4 ) / rc)
#define aij_out (( 4 ) / rc)
#define aij_rbc (( 4 ) / rc)
#define aij_wall (( 4 ) / rc)
#define contactforces ( 0 )
#define doublepoiseuille ( 0 )
#define dt ( 0.0008 )
#define gamma_dot ( 5 )
#define gammadpd_in ( 20 )
#define gammadpd_in_out ( 10 )
#define gammadpd_out ( 30 )
#define gammadpd_rbc ( 30 )
#define gammadpd_wall ( 30 )
#define hdf5field_dumps ( 0 )
#define hdf5part_dumps ( 1 )
#define hydrostatic_a (( 0.05 ) / rc)
#define kBT (( 0.1 ) / (rc*rc))
#define ljepsilon (( 1 ) / (rc*rc))
#define ljsigma ( 0.3 )
#define nosolvent ( 0 )
#define numberdensity (( 3 ) * (rc*rc*rc))
#define pushtheflow ( 0 )
#define rbc_mass ( 0.5 )
#define rbcs ( 1 )
#define rc ( 1.5 )
#define steps_per_dump ( 480 )
#define steps_per_hdf5dump ( 480 )
#define strVerts ( 10 )
#define stretchingForce (( 0 ) / rc)
#define tend ( 480 )
#define wall_creation_stepid ( 100 )
#define walls ( 1 )
