#!/bin/bash

# Usage:
# ./gcp <remote dir>
# ./gcp username@panda.ethz.ch:~/remote-dir

# Create temporary directory with copy of all files under version
# control and copies it to <remote dir>


# copy command
cpy=rsync
cpy_args="-q -r -avz"

# git command
GIT=${GIT:-git}
GITFLAGS="--depth 1"

# default git root directory name on a remote host
default_dir=$1
target=$2

function msg() {
    printf -- "(gcp) $@"  > "/dev/stderr"
}

thost=${target%:*}
tpath=${target##*:}

top=$(${GIT} rev-parse --show-toplevel)
msg "I think top level git directory is ${top}\n"

file_list=$(mktemp  /tmp/gcp.flist.XXXXXX)
dir_list=$(mktemp  /tmp/gcp.dlist.XXXXXX)
local_target=$(mktemp -d /tmp/gcp.XXXXXX)
local_target="${local_target}/${default_dir}"
mkdir -p -- "${local_target}"

msg "Host   name: %s\n" "${thost}"
msg "Remote path: %s\n" "${tpath}"

branch=`"${GIT}" rev-parse --abbrev-ref HEAD`
revid=`"${GIT}" rev-parse HEAD`

msg "Current branch: %s\n" "${branch}"
"${GIT}" clone ${GITFLAGS} -b "${branch}" -- file://"${top}" "${local_target}"
msg "Current id    : %s\n" "${revid}"

msg "Create a list of all staged files: %s\n" "${file_list}"

function create_list() {
    msg "Create a list of all staged directories: %s\n" "${dir_list}"
    awk 'NR' "${file_list}" | xargs -n 1 -I {} dirname "{}" | sort | uniq  | grep . > "${dir_list}"
    "${GIT}" ls-files --cached --full-name  > "${file_list}"
}

function copy_directory_structure() {
    msg "Copy directory structure to %s\n" "${local_target}"
    xargs  -I {}   mkdir -p -- "${local_target}/{}"           < "${dir_list}"
}

function copy_staged_files() {
    msg "Copy staged files to %s\n" "${local_target}"
    while read fname; do
	test -r "${fname}" && cp -- "${fname}" "${local_target}/${fname}"
    done < "${file_list}"
}

(
    cd "${top}"
    create_list
    copy_directory_structure
    copy_staged_files
)

msg "Copying directory from %s to %s\n" "${local_target}" "${target}"
ssh "${thost}" "test -d ${tpath} || mkdir -p ${tpath}"
"${cpy}" ${cpy_args} -- "${local_target}" "${target}"
